site_name: Eastar's android develop
site_author: Eastar Jeong
site_description: A blog created to help others with what I have organized while developing Android.
repo_url: https://github.com/eastar-dev
edit_uri: ""
site_url: https://eastar-dev.github.io/
repo_name: eastar-dev
docs_dir: source
site_dir: docs

extra:
  analytics:
    provider: google
    property: G-PM107R0BGH
  disqus: eastar-dev
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/eastar-dev
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/eastarj/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/eastar.jeong

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.tabbed
  - pymdownx.superfences
  - footnotes
  - pymdownx.snippets
  - pymdownx.tasklist:
      clickable_checkbox: true
      custom_checkbox: true
  - meta
  - toc:
      permalink: "#"

theme:
  name: material
  font:
    text: Nanum Gothic
    code: Roboto Mono
  logo: assets/logo.svg
  favicon: assets/logo.svg
  features:
    - header.autohide
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      accent: grey
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css
    
